In [1]:
import numpy as np
import pandas as pd

In [3]:
dict={
    "subjects":["python","cpp","java","javascript","html"],
    "rating":[5,2,1,4,2],
}

In [4]:
df=pd.DataFrame(dict)

In [5]:
df

subjects  rating
0      python       5
1         cpp       2
2        java       1
3  javascript       4
4        html       2

In [7]:
df.to_csv("subjects.csv",index=False)

In [10]:
df.head(2)

subjects  rating
0   python       5
1      cpp       2

In [11]:
df.describe()

rating
count  5.000000
mean   2.800000
std    1.643168
min    1.000000
25%    2.000000
50%    2.000000
75%    4.000000
max    5.000000

In [12]:
mydata=pd.read_csv("Bollywood/bollywood.csv")

In [13]:
mydata

Movie      Lead      Rdate  Ocollection  Wcollection  \
0                 Dangal     Aamir  23-Dec-16        29.78       106.95   
1           Wajah Tum Ho   Sharman  16-Dec-16         2.86         7.79   
2                Befikre   Ranveer  09-Dec-16        10.36        34.36   
3              Kahaani 2     Vidya  02-Dec-16         4.25        16.97   
4           Dear Zindagi  Shahrukh  25-Nov-16         8.75        32.50   
..                   ...       ...        ...          ...          ...   
56         Saala Khadoos  Madhavan  29-Jan-16         2.19         9.93   
57            Mastizaade     Sunny  29-Jan-16         5.59        18.45   
58               Airlift    Akshay  22-Jan-16        12.35        44.30   
59  Kyaa Kool Hain Hum 3   Tusshar  22-Jan-16         8.15        20.15   
60                 Wazir   Amitabh  08-Jan-16         5.61        21.01   

    Fwcollection  Tcollection    Verdict  
0         197.53       386.68  Super Hit  
1          10.29        10.29       Flop  
2          48.75        59.30    Average  
3          24.26        30.56    Average  
4          47.00        64.44        Hit  
..           ...          ...        ...  
56         12.63        14.79       Flop  
57         28.74        36.44    Average  
58         83.50       128.10  Super Hit  
59         29.65        30.25    Average  
60         30.05        41.02    Average  

[61 rows x 8 columns]

In [18]:
mydata["Movie"][3]

'Kahaani'

In [19]:
seri=pd.Series(np.random.rand(40))
print(seri)

0     0.943171
1     0.404936
2     0.438457
3     0.944700
4     0.497650
5     0.847027
6     0.502844
7     0.174349
8     0.894338
9     0.749178
10    0.069352
11    0.412582
12    0.897988
13    0.250312
14    0.084861
15    0.779735
16    0.258795
17    0.666170
18    0.999443
19    0.713524
20    0.389508
21    0.746720
22    0.181401
23    0.488201
24    0.083420
25    0.578596
26    0.909122
27    0.762563
28    0.215051
29    0.510800
30    0.257085
31    0.523942
32    0.377331
33    0.671801
34    0.032990
35    0.242491
36    0.159262
37    0.966830
38    0.419321
39    0.982066
dtype: float64


In [20]:
newdf=np.random.rand(3000,5)
print(newdf)

[[0.44955359 0.90805609 0.03036176 0.81896356 0.10771694]
 [0.72292505 0.72932343 0.71603822 0.10369195 0.33127242]
 [0.6216966  0.54887756 0.69494126 0.71051994 0.87298771]
 ...
 [0.83742975 0.46648627 0.75067357 0.06124186 0.46842668]
 [0.29386576 0.55040355 0.73823061 0.73851966 0.12349846]
 [0.88245688 0.61627256 0.46985532 0.60422958 0.3668554 ]]


In [21]:
newdf=pd.DataFrame(newdf)
print(newdf)

             0         1         2         3         4
0     0.449554  0.908056  0.030362  0.818964  0.107717
1     0.722925  0.729323  0.716038  0.103692  0.331272
2     0.621697  0.548878  0.694941  0.710520  0.872988
3     0.505539  0.703869  0.466557  0.217443  0.368813
4     0.119801  0.901359  0.898079  0.528000  0.040531
...        ...       ...       ...       ...       ...
2995  0.582159  0.935148  0.168189  0.013772  0.787753
2996  0.054559  0.530590  0.309385  0.344923  0.020687
2997  0.837430  0.466486  0.750674  0.061242  0.468427
2998  0.293866  0.550404  0.738231  0.738520  0.123498
2999  0.882457  0.616273  0.469855  0.604230  0.366855

[3000 rows x 5 columns]


In [25]:
type(newdf)

pandas.core.frame.DataFrame

In [26]:
print(newdf.describe())

                 0            1            2            3            4
count  3000.000000  3000.000000  3000.000000  3000.000000  3000.000000
mean      0.495110     0.497873     0.502721     0.494363     0.493310
std       0.287222     0.288967     0.287712     0.287298     0.285967
min       0.000072     0.000031     0.000081     0.000718     0.000011
25%       0.244645     0.251745     0.251665     0.242898     0.239730
50%       0.490638     0.491838     0.506705     0.494235     0.502687
75%       0.740730     0.743999     0.743368     0.746508     0.732994
max       0.999421     0.999917     0.999900     0.999930     0.999648


In [29]:
newdf.head(5)

0         1         2         3         4
0  0.449554  0.908056  0.030362  0.818964  0.107717
1  0.722925  0.729323  0.716038  0.103692  0.331272
2  0.621697  0.548878  0.694941  0.710520  0.872988
3  0.505539  0.703869  0.466557  0.217443  0.368813
4  0.119801  0.901359  0.898079  0.528000  0.040531

In [30]:
newdf[0][2]="gourav"

In [32]:
newdf.head(5)

0         1         2         3         4
0  0.449554  0.908056  0.030362  0.818964  0.107717
1  0.722925  0.729323  0.716038  0.103692  0.331272
2    gourav  0.548878  0.694941  0.710520  0.872988
3  0.505539  0.703869  0.466557  0.217443  0.368813
4  0.119801  0.901359  0.898079  0.528000  0.040531

In [35]:
print(type(newdf))

<class 'pandas.core.frame.DataFrame'>


In [36]:
newdf.index

RangeIndex(start=0, stop=3000, step=1)

In [38]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [41]:
newdf.sort_index(axis=1,ascending=False)

4         3         2         1         0
0     0.107717  0.818964  0.030362  0.908056  0.449554
1     0.331272  0.103692  0.716038  0.729323  0.722925
2     0.872988  0.710520  0.694941  0.548878    gourav
3     0.368813  0.217443  0.466557  0.703869  0.505539
4     0.040531  0.528000  0.898079  0.901359  0.119801
...        ...       ...       ...       ...       ...
2995  0.787753  0.013772  0.168189  0.935148  0.582159
2996  0.020687  0.344923  0.309385  0.530590  0.054559
2997  0.468427  0.061242  0.750674  0.466486   0.83743
2998  0.123498  0.738520  0.738231  0.550404  0.293866
2999  0.366855  0.604230  0.469855  0.616273  0.882457

[3000 rows x 5 columns]

In [44]:
print(type(newdf[0]))

<class 'pandas.core.series.Series'>


In [45]:
newdff=newdf.copy()

In [47]:
newdff[0][0]=445

C:\Users\ADMINI~1\AppData\Local\Temp/ipykernel_2340/1371216946.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdff[0][0]=445


In [48]:
newdff

0         1         2         3         4
0          445  0.908056  0.030362  0.818964  0.107717
1     0.722925  0.729323  0.716038  0.103692  0.331272
2       gourav  0.548878  0.694941  0.710520  0.872988
3     0.505539  0.703869  0.466557  0.217443  0.368813
4     0.119801  0.901359  0.898079  0.528000  0.040531
...        ...       ...       ...       ...       ...
2995  0.582159  0.935148  0.168189  0.013772  0.787753
2996  0.054559  0.530590  0.309385  0.344923  0.020687
2997   0.83743  0.466486  0.750674  0.061242  0.468427
2998  0.293866  0.550404  0.738231  0.738520  0.123498
2999  0.882457  0.616273  0.469855  0.604230  0.366855

[3000 rows x 5 columns]

In [49]:
newdff.loc[1,0]=555

In [50]:
newdff 

0         1         2         3         4
0          445  0.908056  0.030362  0.818964  0.107717
1          555  0.729323  0.716038  0.103692  0.331272
2       gourav  0.548878  0.694941  0.710520  0.872988
3     0.505539  0.703869  0.466557  0.217443  0.368813
4     0.119801  0.901359  0.898079  0.528000  0.040531
...        ...       ...       ...       ...       ...
2995  0.582159  0.935148  0.168189  0.013772  0.787753
2996  0.054559  0.530590  0.309385  0.344923  0.020687
2997   0.83743  0.466486  0.750674  0.061242  0.468427
2998  0.293866  0.550404  0.738231  0.738520  0.123498
2999  0.882457  0.616273  0.469855  0.604230  0.366855

[3000 rows x 5 columns]

In [51]:
newdff.columns=["fir","sec","third","fourth","fifth"]

In [52]:
newdff

fir       sec     third    fourth     fifth
0          445  0.908056  0.030362  0.818964  0.107717
1          555  0.729323  0.716038  0.103692  0.331272
2       gourav  0.548878  0.694941  0.710520  0.872988
3     0.505539  0.703869  0.466557  0.217443  0.368813
4     0.119801  0.901359  0.898079  0.528000  0.040531
...        ...       ...       ...       ...       ...
2995  0.582159  0.935148  0.168189  0.013772  0.787753
2996  0.054559  0.530590  0.309385  0.344923  0.020687
2997   0.83743  0.466486  0.750674  0.061242  0.468427
2998  0.293866  0.550404  0.738231  0.738520  0.123498
2999  0.882457  0.616273  0.469855  0.604230  0.366855

[3000 rows x 5 columns]

In [56]:
newdff[5,sec]=2222

In [57]:
newdff.head(5)

fir       sec     third    fourth     fifth  (5, sec)
0       445  0.908056  0.030362  0.818964  0.107717      2222
1       555  0.729323  0.716038  0.103692  0.331272      2222
2    gourav  0.548878  0.694941  0.710520  0.872988      2222
3  0.505539  0.703869  0.466557  0.217443  0.368813      2222
4  0.119801  0.901359  0.898079  0.528000  0.040531      2222

In [65]:
newdff.columns

Index(['fir', 'sec', 'third', 'fourth', 'fifth', (5, 'sec')], dtype='object')

In [69]:
newdff.drop((5,"sec"),axis=1)

fir       sec     third    fourth     fifth
0          445  0.908056  0.030362  0.818964  0.107717
1          555  0.729323  0.716038  0.103692  0.331272
2       gourav  0.548878  0.694941  0.710520  0.872988
3     0.505539  0.703869  0.466557  0.217443  0.368813
4     0.119801  0.901359  0.898079  0.528000  0.040531
...        ...       ...       ...       ...       ...
2995  0.582159  0.935148  0.168189  0.013772  0.787753
2996  0.054559  0.530590  0.309385  0.344923  0.020687
2997   0.83743  0.466486  0.750674  0.061242  0.468427
2998  0.293866  0.550404  0.738231  0.738520  0.123498
2999  0.882457  0.616273  0.469855  0.604230  0.366855

[3000 rows x 5 columns]

In [78]:
newdff.loc[[1,4],:]

fir       sec     third    fourth     fifth  (5, sec)
1       555  0.729323  0.716038  0.103692  0.331272      2222
4  0.119801  0.901359  0.898079  0.528000  0.040531      2222

In [88]:
print(type(newdff.loc[(newdff["sec"]<0.3)]))

<class 'pandas.core.frame.DataFrame'>


In [89]:
#this is for iloc function

In [93]:
newdf.iloc[3,4]

0.3688127532792119

In [94]:
newdff

fir       sec     third    fourth     fifth  (5, sec)
0          445  0.908056  0.030362  0.818964  0.107717      2222
1          555  0.729323  0.716038  0.103692  0.331272      2222
2       gourav  0.548878  0.694941  0.710520  0.872988      2222
3     0.505539  0.703869  0.466557  0.217443  0.368813      2222
4     0.119801  0.901359  0.898079  0.528000  0.040531      2222
...        ...       ...       ...       ...       ...       ...
2995  0.582159  0.935148  0.168189  0.013772  0.787753      2222
2996  0.054559  0.530590  0.309385  0.344923  0.020687      2222
2997   0.83743  0.466486  0.750674  0.061242  0.468427      2222
2998  0.293866  0.550404  0.738231  0.738520  0.123498      2222
2999  0.882457  0.616273  0.469855  0.604230  0.366855      2222

[3000 rows x 6 columns]

In [97]:
newdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       3000 non-null   object 
 1   1       3000 non-null   float64
 2   2       3000 non-null   float64
 3   3       3000 non-null   float64
 4   4       3000 non-null   float64
dtypes: float64(4), object(1)
memory usage: 105.5+ KB


In [101]:
data=np.random.rand(3,2)

In [103]:
data=pd.DataFrame(data)

In [104]:
data

0         1
0  0.929501  0.317953
1  0.582886  0.771927
2  0.604922  0.850462

In [105]:
data.describe()

0         1
count  3.000000  3.000000
mean   0.705770  0.646781
std    0.194070  0.287468
min    0.582886  0.317953
25%    0.593904  0.544940
50%    0.604922  0.771927
75%    0.767212  0.811195
max    0.929501  0.850462

In [106]:
data.mean()

0    0.705770
1    0.646781
dtype: float64

In [107]:
data.corr()

0         1
0  1.000000 -0.981274
1 -0.981274  1.000000

In [108]:
data.count()

0    3
1    3
dtype: int64

In [109]:
data.max()

0    0.929501
1    0.850462
dtype: float64

In [111]:
data.min()

0    0.582886
1    0.317953
dtype: float64

In [112]:
data.std()

0    0.194070
1    0.287468
dtype: float64

In [114]:
data.median()

0    0.604922
1    0.771927
dtype: float64